### PR TITLE
Only compile python bindings with C++17

### LINKED ISSUE #74: `response_array` Python build error on Ubuntu
## Description
Building the latest commit fails as `response_array` was used without being declared in `external/org_openmined_psi/private_set_intersection/cpp/psi_client.cpp`.

See [this build](https://github.com/OpenMined/PyVertical/runs/862412117?check_suite_focus=true) in PyVertical

Our workspace file is:
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
   name = "org_openmined_psi",
   remote = "https://github.com/OpenMined/PSI",
   commit = "2110b0c78aaf535f0f154541a5239ae1d4876023",
   init_submodules = True,
)

load("@org_openmined_psi//private_set_intersection:preload.bzl", "psi_preload")

psi_preload()

load("@org_openmined_psi//private_set_intersection:deps.bzl", "psi_deps")

psi_deps()
```

and we build by running
```
bazel build @org_openmined_psi//private_set_intersection/python:private_set_intersection
```

## How to Reproduce
1. Attempt to build the Python code for the latest commit

## Expected Behavior
Build should pass

## Screenshots
image

## System Information
 - OS: Ubuntu
 - OS Version: 18.04
 - Language Version: Python 3.6,3.7,3.8

### PR DESCRIPTION
**Pull request by schoppmp**
## Description
We don't want to fix a C++ version in .bazelrc. Instead, only targets that need C++17 (currently only `//private_set_intersection/python:__psi_bindings`) should specify it in their `copts `attribute, and all other targest should be C++11 compliant.

Fixes #74 

## Affected Dependencies
None

## How has this been tested?
`bazel test`

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by schoppmp** [comment]
@s0l0ist I think I was wrong to request the type for the Protobuf arrays to be specified explicitly. For C++11 compatibility, we would also need to include the template argument, and then it would become really long. So I went back to `const auto&` again, as you proposed in the beginning.

I also simplified the sorting in `PsiServer::ProcessRequest` by sorting the protobuf array directly.

File: private_set_intersection/cpp/psi_server.cpp [hunk 1]
```diff
@@ -112,14 +111,9 @@ StatusOr<psi_proto::Response> PsiServer::ProcessRequest(
...
-    const google::protobuf::RepeatedPtrField elements =
-        response.encrypted_elements();
-    // Create a copy to mutate
-    google::protobuf::RepeatedPtrField sorted_elements = elements;
-    std::sort(sorted_elements.begin(), sorted_elements.end());
-    for (int i = 0; i < num_client_elements; i++) {
-      response.set_encrypted_elements(i, sorted_elements[i]);
-    }
+    // Get mutable reference to encrypted_elements array and sort it.
+    auto& elements = *(response.mutable_encrypted_elements());
```
Comment (s0l0ist) [inline private_set_intersection/cpp/psi_server.cpp:115]: Awesome. Didn’t realize this function was exposed.

**Comment by TTitcombe** [comment]
Fixes the issue on PyVertical (see this build https://github.com/OpenMined/PyVertical/pull/51/checks?check_run_id=870098743)
